name: Build Release APK

on:
  push:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > app/keystore.jks
          chmod 644 app/keystore.jks

      - name: Configure local.properties
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> local.properties
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> local.properties
          echo "STORE_FILE=keystore.jks" >> local.properties
          echo "STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> local.properties
          echo "MAPKIT_API_KEY=${{ secrets.MAPKIT_API_KEY }}" >> local.properties

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
         name: SocialApp-release.apk
         path: app/build/outputs/apk/release/*.apk